# Form implementation generated from reading ui file 'SearchData.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import mysql.connector as mc


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 450)
        self.formLayout = QtWidgets.QFormLayout(Form)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.label)
        self.label_dbname = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_dbname.setFont(font)
        self.label_dbname.setObjectName("label_dbname")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_dbname)
        self.lineEdit_dbname = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_dbname.setObjectName("lineEdit_dbname")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_dbname)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.formLayout.setItem(2, QtWidgets.QFormLayout.ItemRole.FieldRole, spacerItem)
        self.label_tblname = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_tblname.setFont(font)
        self.label_tblname.setObjectName("label_tblname")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_tblname)
        self.lineEdit_tblname = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_tblname.setObjectName("lineEdit_tblname")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_tblname)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.formLayout.setItem(4, QtWidgets.QFormLayout.ItemRole.FieldRole, spacerItem1)
        self.label_username = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_username.setFont(font)
        self.label_username.setObjectName("label_username")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_username)
        self.lineEdit_username = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_username)
        spacerItem2 = QtWidgets.QSpacerItem(0, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.formLayout.setItem(6, QtWidgets.QFormLayout.ItemRole.FieldRole, spacerItem2)
        self.pushButton_search = QtWidgets.QPushButton(parent=Form)

        #connect signal
        self.pushButton_search.clicked.connect(self.search_data)


        self.pushButton_search.setObjectName("pushButton_search")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.ItemRole.FieldRole, self.pushButton_search)
        self.label_password = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_password.setFont(font)
        self.label_password.setObjectName("label_password")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_password)
        self.lineEdit_password = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_password)
        self.label_result = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_result.setFont(font)
        self.label_result.setText("")
        self.label_result.setObjectName("label_result")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.label_result)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def search_data(self):
        dbname = self.lineEdit_dbname.text()  # Get the text from the line edit widget
        try:
            mydb = mc.connect(
                host="localhost",
                user="root",
                password="",
                database=dbname
            )

            query = "SELECT password FROM " + self.lineEdit_tblname.text() + " where username like '" + self.lineEdit_username.text() + "'"
            mycursor = mydb.cursor()
            mycursor.execute(query)

            row = mycursor.fetchone()

            if row is None:
                self.label_result.setText("No user found with this username")
                self.label_result.setStyleSheet("color: red")
                self.lineEdit_password.setText("")

            else:
                self.label_result.setText("Username has been found")
                self.label_result.setStyleSheet("color: green")
                self.lineEdit_password.setText(row[0])

        except mc.Error as e:
            self.label_result.setText("Error in connection")
            self.label_result.setStyleSheet("color: red")

        


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Search Data from Database"))
        self.label_dbname.setText(_translate("Form", "Database Name"))
        self.label_tblname.setText(_translate("Form", "Table Name"))
        self.label_username.setText(_translate("Form", "User Name"))
        self.pushButton_search.setText(_translate("Form", "Search Data"))
        self.label_password.setText(_translate("Form", "Password"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
