# Form implementation generated from reading ui file 'SimpleLogin.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QDialog
from PyQt6.QtGui import QIcon
import mysql.connector as mc


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        
    
        self.label_3 = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        # Set the text alignment to center (both horizontally and vertically)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
         # Set top and bottom margins for the label using style sheet
        self.label_3.setStyleSheet("margin-top: 0px; margin-bottom: 0px;")
        self.verticalLayout.addWidget(self.label_3)
        
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_username = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.lineEdit_username.setStyleSheet("margin-top: 0px; margin-bottom: 10px;")
        self.horizontalLayout.addWidget(self.lineEdit_username)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_password = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_password.setMaxLength(8)
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.horizontalLayout_2.addWidget(self.lineEdit_password)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.pushButton_login = QtWidgets.QPushButton(parent=Form)
        self.pushButton_login.setObjectName("pushButton_login")
        
        #connect signal
        self.pushButton_login.clicked.connect(self.login)
        
        self.verticalLayout.addWidget(self.pushButton_login)
        self.label_result = QtWidgets.QLabel(parent=Form)
        self.label_result.setText("")
        self.label_result.setObjectName("label_result")
        self.verticalLayout.addWidget(self.label_result)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        
    def login(self):
        
        username = self.lineEdit_username.text()
        password = self.lineEdit_password.text()
        
        try:
            mydb = mc.connect(
                host="localhost",
                user="root",
                password="",
                database="pyqtdb"
            )
            
            mycursor = mydb.cursor()
            query = "SELECT username, password from pyqtusers where username like '"+ username +"'and password like '"+ password +"'"
            mycursor.execute(query)
            
            result = mycursor.fetchone()
            
            if result == None:
                self.label_result.setText("Incorrect email or password")
                self.label_result.setStyleSheet("color: red")
                
            else:
                self.label_result.setText("You are logged in")
                self.label_result.setStyleSheet("color: green")
                mydialog = QDialog()
                mydialog.setModal(True)
                mydialog.exec()
            
        except mc.Error as e:
            self.label_result.setText("Error")

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "Login with MySQL & PyQt6"))
        self.label.setText(_translate("Form", "Username:"))
        self.label_2.setText(_translate("Form", "Password: "))
        self.pushButton_login.setText(_translate("Form", "Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
