# Form implementation generated from reading ui file 'DashboardTestDemo.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(863, 634)
        MainWindow.setStyleSheet("#sidemenu {\n"
"background-color: #063d40\n"
"}\n"
"\n"
"#sidemenu QPushButton{\n"
"border: none;\n"
"color: #fff;\n"
"text-align: left;\n"
"padding: 5px;\n"
"\n"
"}\n"
"#menuframe{\n"
"border-top: 2px solid #0a676c;\n"
"}\n"
"#menuframe QFrame:hover,\n"
"#newconversation QFrame:hover{\n"
"background-color:#0a676c;\n"
"color: black;\n"
"}\n"
"#logo_section QFrame{\n"
"background:#F0F8FF;\n"
"border-radius: 5px;\n"
"}\n"
"#login_section QPushButton{\n"
"color: #0a676c;\n"
"}\n"
"\n"
"#newconversation QFrame{\n"
"border: 2px solid #0a676c;\n"
"}\n"
"#menuframe QFrame, \n"
"#newconversation QFrame{\n"
"border-radius: 5px;\n"
"}\n"
"#chatlist{\n"
"background: #063d40;\n"
"border:noe;\n"
"}\n"
"\n"
"#header{\n"
"background-color: #abb2b9\n"
"}\n"
"#header QPushButton {\n"
"border: none;\n"
"background-color: transparent;\n"
"}\n"
"\n"
"#input_frame{\n"
"border: 1px solid #e5e5e5;\n"
"background: #fff;\n"
"border-radius: 10px;\n"
"\n"
"}\n"
"#input_textEdit {\n"
"border: none;\n"
"padding-top: 5px;\n"
"}\n"
"#send_btn{\n"
"border: none;\n"
"padding: 5px;\n"
"border-radius: 5px;\n"
"}\n"
"#send_btn:hover{\n"
"background: #ececf1;\n"
"}\n"
"#main_scrollArea{\n"
"border:none;\n"
"}\n"
"\n"
"#right_main_widget,\n"
"#scrollAreaWidgetContents{\n"
"background: #F0F8FF;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonIconOnly)
        MainWindow.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.sidemenu = QtWidgets.QWidget(parent=self.centralwidget)
        self.sidemenu.setMaximumSize(QtCore.QSize(220, 16777215))
        self.sidemenu.setObjectName("sidemenu")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.sidemenu)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.logo_section = QtWidgets.QFrame(parent=self.sidemenu)
        self.logo_section.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.logo_section.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.logo_section.setObjectName("logo_section")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.logo_section)
        self.verticalLayout_4.setContentsMargins(-1, 9, -1, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_8 = QtWidgets.QFrame(parent=self.logo_section)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frame_8.setFont(font)
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_6.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(parent=self.frame_8)
        self.label_6.setMinimumSize(QtCore.QSize(38, 20))
        self.label_6.setMaximumSize(QtCore.QSize(38, 20))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("icons/main-logo.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.frame_8)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(False)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("color: #0a676c;")
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_6.addWidget(self.pushButton_6)
        self.verticalLayout_4.addWidget(self.frame_8)
        self.verticalLayout_6.addWidget(self.logo_section)
        self.newconversation = QtWidgets.QFrame(parent=self.sidemenu)
        self.newconversation.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.newconversation.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.newconversation.setObjectName("newconversation")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.newconversation)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(parent=self.newconversation)
        self.frame.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton = QtWidgets.QPushButton(parent=self.frame)
        font = QtGui.QFont()
        font.setBold(True)
        self.pushButton.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/plus.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(18, 18))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_5.addWidget(self.pushButton)
        self.verticalLayout_3.addWidget(self.frame)
        self.verticalLayout_6.addWidget(self.newconversation)
        self.frame_2 = QtWidgets.QFrame(parent=self.sidemenu)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.chatlist = QtWidgets.QListView(parent=self.frame_2)
        self.chatlist.setObjectName("chatlist")
        self.verticalLayout_2.addWidget(self.chatlist)
        self.verticalLayout_6.addWidget(self.frame_2)
        self.menuframe = QtWidgets.QFrame(parent=self.sidemenu)
        self.menuframe.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.menuframe.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.menuframe.setObjectName("menuframe")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.menuframe)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_4 = QtWidgets.QFrame(parent=self.menuframe)
        self.frame_4.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.frame_4)
        self.label.setMaximumSize(QtCore.QSize(18, 18))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("icons/trash-2.svg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.frame_4)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(parent=self.menuframe)
        self.frame_5.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_2.setMaximumSize(QtCore.QSize(18, 18))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("icons/settings.svg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.frame_5)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.verticalLayout.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(parent=self.menuframe)
        self.frame_6.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_3.setMaximumSize(QtCore.QSize(18, 18))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("icons/moon.svg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.frame_6)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_3.addWidget(self.pushButton_4)
        self.verticalLayout.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(parent=self.menuframe)
        self.frame_7.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(parent=self.frame_7)
        self.label_4.setMaximumSize(QtCore.QSize(18, 18))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("icons/log-out (1).svg"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.frame_7)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_4.addWidget(self.pushButton_5)
        self.verticalLayout.addWidget(self.frame_7)
        self.verticalLayout_6.addWidget(self.menuframe)
        self.horizontalLayout_9.addWidget(self.sidemenu)
        self.right_main_widget = QtWidgets.QWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.right_main_widget.sizePolicy().hasHeightForWidth())
        self.right_main_widget.setSizePolicy(sizePolicy)
        self.right_main_widget.setMinimumSize(QtCore.QSize(600, 550))
        self.right_main_widget.setObjectName("right_main_widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.right_main_widget)
        self.verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.header = QtWidgets.QWidget(parent=self.right_main_widget)
        self.header.setMinimumSize(QtCore.QSize(0, 50))
        self.header.setMaximumSize(QtCore.QSize(16777215, 50))
        self.header.setObjectName("header")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.header)
        self.horizontalLayout_10.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.frame_3 = QtWidgets.QFrame(parent=self.header)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.frame_3)
        self.pushButton_8.setText("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_11.addWidget(self.pushButton_8)
        self.horizontalLayout_10.addWidget(self.frame_3)
        spacerItem = QtWidgets.QSpacerItem(594, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.frame_11 = QtWidgets.QFrame(parent=self.header)
        self.frame_11.setMinimumSize(QtCore.QSize(30, 30))
        self.frame_11.setMaximumSize(QtCore.QSize(30, 30))
        self.frame_11.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.pushButton_9 = QtWidgets.QPushButton(parent=self.frame_11)
        self.pushButton_9.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/profile.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_9.setIcon(icon1)
        self.pushButton_9.setIconSize(QtCore.QSize(28, 28))
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_12.addWidget(self.pushButton_9)
        self.horizontalLayout_10.addWidget(self.frame_11)
        self.verticalLayout_5.addWidget(self.header)
        self.message_area = QtWidgets.QWidget(parent=self.right_main_widget)
        self.message_area.setObjectName("message_area")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.message_area)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_9 = QtWidgets.QFrame(parent=self.message_area)
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.main_scrollArea = QtWidgets.QScrollArea(parent=self.frame_9)
        self.main_scrollArea.setWidgetResizable(True)
        self.main_scrollArea.setObjectName("main_scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 651, 502))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 425, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem1, 0, 0, 1, 1)
        self.main_scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_8.addWidget(self.main_scrollArea)
        self.verticalLayout_7.addWidget(self.frame_9)
        self.frame_10 = QtWidgets.QFrame(parent=self.message_area)
        self.frame_10.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_10.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_10.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem2 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem2)
        self.input_frame = QtWidgets.QFrame(parent=self.frame_10)
        self.input_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.input_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.input_frame.setObjectName("input_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.input_frame)
        self.gridLayout_2.setContentsMargins(-1, 9, -1, 9)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.input_textEdit = QtWidgets.QTextEdit(parent=self.input_frame)
        self.input_textEdit.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.input_textEdit.setFont(font)
        self.input_textEdit.setObjectName("input_textEdit")
        self.gridLayout_2.addWidget(self.input_textEdit, 0, 0, 1, 1)
        self.send_btn = QtWidgets.QPushButton(parent=self.input_frame)
        self.send_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.send_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.send_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.send_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/send-message (2).png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.send_btn.setIcon(icon2)
        self.send_btn.setIconSize(QtCore.QSize(18, 18))
        self.send_btn.setObjectName("send_btn")
        self.gridLayout_2.addWidget(self.send_btn, 0, 1, 1, 1)
        self.horizontalLayout_13.addWidget(self.input_frame)
        spacerItem3 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem3)
        self.verticalLayout_7.addWidget(self.frame_10)
        self.verticalLayout_5.addWidget(self.message_area)
        self.horizontalLayout_9.addWidget(self.right_main_widget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_6.setText(_translate("MainWindow", "SOBJANTA"))
        self.pushButton.setText(_translate("MainWindow", "New Conversation"))
        self.pushButton_2.setText(_translate("MainWindow", "Clear History"))
        self.pushButton_3.setText(_translate("MainWindow", "Setting"))
        self.pushButton_4.setText(_translate("MainWindow", "Mode"))
        self.pushButton_5.setText(_translate("MainWindow", "Log Out"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
