# Form implementation generated from reading ui file 'TestDemoLogin.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(457, 361)
        Form.setStyleSheet("#Form{\n"
"background-color:#0a676c\n"
"}\n"
"\n"
"#loginwidget{\n"
"background-color: #fff;\n"
"border-radius: 10px\n"
"}\n"
"\n"
"#logo_frame QPushButton{\n"
"background-color: transparent;\n"
"}\n"
"#title_frame QPushButton{\n"
"text-align: center;\n"
"background-color: transparent;\n"
"border: none;\n"
"color: #0a676c;\n"
"}\n"
"")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(7, -1, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.loginwidget = QtWidgets.QWidget(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loginwidget.sizePolicy().hasHeightForWidth())
        self.loginwidget.setSizePolicy(sizePolicy)
        self.loginwidget.setMaximumSize(QtCore.QSize(441, 343))
        self.loginwidget.setObjectName("loginwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.loginwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.logo_frame = QtWidgets.QFrame(parent=self.loginwidget)
        self.logo_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.logo_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.logo_frame.setObjectName("logo_frame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.logo_frame)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.logo = QtWidgets.QPushButton(parent=self.logo_frame)
        self.logo.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(13)
        font.setBold(False)
        self.logo.setFont(font)
        self.logo.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/logo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.logo.setIcon(icon)
        self.logo.setIconSize(QtCore.QSize(70, 35))
        self.logo.setObjectName("logo")
        self.horizontalLayout_7.addWidget(self.logo)
        self.verticalLayout_2.addWidget(self.logo_frame)
        self.title_frame = QtWidgets.QFrame(parent=self.loginwidget)
        self.title_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.title_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.title_frame.setObjectName("title_frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.title_frame)
        self.horizontalLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton = QtWidgets.QPushButton(parent=self.title_frame)
        self.pushButton.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(17)
        font.setBold(False)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_6.addWidget(self.pushButton)
        self.verticalLayout_2.addWidget(self.title_frame)
        self.loginframe_user = QtWidgets.QFrame(parent=self.loginwidget)
        self.loginframe_user.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.loginframe_user.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.loginframe_user.setObjectName("loginframe_user")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.loginframe_user)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        self.verticalLayout.addItem(spacerItem)
        self.username_frame = QtWidgets.QFrame(parent=self.loginframe_user)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.username_frame.setFont(font)
        self.username_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.username_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.username_frame.setObjectName("username_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.username_frame)
        self.horizontalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_username = QtWidgets.QLineEdit(parent=self.username_frame)
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.horizontalLayout_2.addWidget(self.lineEdit_username)
        self.verticalLayout.addWidget(self.username_frame)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        self.verticalLayout.addItem(spacerItem1)
        self.password_frame = QtWidgets.QFrame(parent=self.loginframe_user)
        self.password_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.password_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.password_frame.setObjectName("password_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.password_frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit_password = QtWidgets.QLineEdit(parent=self.password_frame)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.horizontalLayout_3.addWidget(self.lineEdit_password)
        self.verticalLayout.addWidget(self.password_frame)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        self.verticalLayout.addItem(spacerItem2)
        self.login_btn_frame = QtWidgets.QFrame(parent=self.loginframe_user)
        self.login_btn_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.login_btn_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.login_btn_frame.setObjectName("login_btn_frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.login_btn_frame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.login_btn = QtWidgets.QPushButton(parent=self.login_btn_frame)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/log-in (1).svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.login_btn.setIcon(icon1)
        self.login_btn.setObjectName("login_btn")
        self.horizontalLayout_4.addWidget(self.login_btn)
        self.verticalLayout.addWidget(self.login_btn_frame)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        self.verticalLayout.addItem(spacerItem3)
        self.verticalLayout_2.addWidget(self.loginframe_user)
        self.message_frame = QtWidgets.QFrame(parent=self.loginwidget)
        self.message_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.message_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.message_frame.setObjectName("message_frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.message_frame)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_message = QtWidgets.QLabel(parent=self.message_frame)
        self.label_message.setObjectName("label_message")
        self.horizontalLayout_5.addWidget(self.label_message)
        self.verticalLayout_2.addWidget(self.message_frame)
        self.horizontalLayout.addWidget(self.loginwidget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "LOGIN ACCOUNT"))
        self.lineEdit_username.setPlaceholderText(_translate("Form", "Enter Username"))
        self.lineEdit_password.setPlaceholderText(_translate("Form", "Enter Password"))
        self.login_btn.setText(_translate("Form", "LOG IN"))
        self.label_message.setText(_translate("Form", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
