# Form implementation generated from reading ui file 'c:\Users\MD. SHAMIM\Documents\GitHub\Python-GUI-PyQt6\Section-02\RadioButtonGroup.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        Dialog.setStyleSheet("QLabel {\n"
"color: purple\n"
"}")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(9, 9, 164, 26))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_result = QtWidgets.QLabel(parent=Dialog)
        self.label_result.setGeometry(QtCore.QRect(9, 254, 382, 37))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_result.setFont(font)
        self.label_result.setText("")
        self.label_result.setObjectName("label_result")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(9, 132, 223, 26))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.widget = QtWidgets.QWidget(parent=Dialog)
        self.widget.setGeometry(QtCore.QRect(9, 52, 96, 74))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(20, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.python_radio = QtWidgets.QRadioButton(parent=self.widget)
        self.python_radio.setObjectName("python_radio")
        self.verticalLayout.addWidget(self.python_radio)
        #signal connection
        self.python_radio.toggled.connect(self.radio_selected)

        self.java_radio = QtWidgets.QRadioButton(parent=self.widget)
        self.java_radio.setObjectName("java_radio")
        self.verticalLayout.addWidget(self.java_radio)
        #signal connection
        self.java_radio.toggled.connect(self.radio_selected)

        self.javascript_radio = QtWidgets.QRadioButton(parent=self.widget)
        self.javascript_radio.setObjectName("javascript_radio")
        self.verticalLayout.addWidget(self.javascript_radio)
         #signal connection
        self.javascript_radio.toggled.connect(self.radio_selected)

        self.widget1 = QtWidgets.QWidget(parent=Dialog)
        self.widget1.setGeometry(QtCore.QRect(9, 174, 75, 74))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(20, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.card_radio = QtWidgets.QRadioButton(parent=self.widget1)
        self.card_radio.setObjectName("card_radio")
        self.verticalLayout_2.addWidget(self.card_radio)
        #signal connection
        self.card_radio.toggled.connect(self.radio_selected)

        self.bkash_radio = QtWidgets.QRadioButton(parent=Dialog)
        self.bkash_radio.setObjectName("bkash_radio")
        self.verticalLayout_2.addWidget(self.bkash_radio)
        #signal connection
        self.bkash_radio.toggled.connect(self.radio_selected)

        self.cash_radio = QtWidgets.QRadioButton(parent=Dialog)
        self.cash_radio.setObjectName("cash_radio")
        self.verticalLayout_2.addWidget(self.cash_radio)
        #signal connection
        self.cash_radio.toggled.connect(self.radio_selected)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    

    def radio_selected(self):
        book_selected = ""
        payment_selected = ""

        if self.python_radio.isChecked() == True:
            book_selected = "Python"
        if self.javascript_radio.isChecked() == True:
            book_selected = "JavaScript"
        if self.java_radio.isChecked() == True:
            book_selected = "Java"
        if self.card_radio.isChecked() == True:
            payment_selected = "Card"
        if self.bkash_radio.isChecked() == True:
            payment_selected = "Bkash"
        if self.cash_radio.isChecked() == True:
            payment_selected = "Cash"

        self.label_result.setText("Chosen Book- " +book_selected+", Choosen Payment Method- " +payment_selected)
        

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Book Payment"))
        self.label.setText(_translate("Dialog", "Choose Your Book"))
        self.python_radio.setText(_translate("Dialog", "Python"))
        self.java_radio.setText(_translate("Dialog", "Java"))
        self.javascript_radio.setText(_translate("Dialog", "JavaScript"))
        self.label_3.setText(_translate("Dialog", "Choose Payment Method"))
        self.card_radio.setText(_translate("Dialog", "Card"))
        self.bkash_radio.setText(_translate("Dialog", "Bkash"))
        self.cash_radio.setText(_translate("Dialog", "Cash"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
