# Form implementation generated from reading ui file 'Calculator.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(450, 211)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lineEdit_1st = QtWidgets.QLineEdit(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_1st.setFont(font)
        self.lineEdit_1st.setObjectName("lineEdit_1st")
        self.horizontalLayout.addWidget(self.lineEdit_1st)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.lineEdit_2nd = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_2nd.setObjectName("lineEdit_2nd")
        self.horizontalLayout_2.addWidget(self.lineEdit_2nd)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")

        #-----------Addition Section---------------
        self.addbtn = QtWidgets.QPushButton(parent=Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        self.addbtn.setFont(font)
        self.addbtn.setObjectName("addbtn")
        self.addbtn.clicked.connect(self.add)
        self.horizontalLayout_3.addWidget(self.addbtn)

        #-----------Subtraction Section---------------
        self.subtractbtn = QtWidgets.QPushButton(parent=Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        self.subtractbtn.setFont(font)
        self.subtractbtn.setObjectName("subtractbtn")
        self.subtractbtn.clicked.connect(self.subtraction)
        self.horizontalLayout_3.addWidget(self.subtractbtn)

        #-----------Multiplication Section---------------
        self.intobtn = QtWidgets.QPushButton(parent=Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        self.intobtn.setFont(font)
        self.intobtn.setObjectName("intobtn")
        self.intobtn.clicked.connect(self.multiplication)
        self.horizontalLayout_3.addWidget(self.intobtn)

        #-----------dividition Section---------------
        self.dividbtn = QtWidgets.QPushButton(parent=Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        self.dividbtn.setFont(font)
        self.dividbtn.setObjectName("dividbtn")
        self.dividbtn.clicked.connect(self.dividition)
        self.horizontalLayout_3.addWidget(self.dividbtn)


        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.label_result = QtWidgets.QLabel(parent=Form)
        self.label_result.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_result.setFont(font)
        self.label_result.setAutoFillBackground(True)
        self.label_result.setStyleSheet("QLabel {\n"
"color: green\n"
"}")
        self.label_result.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_result.setObjectName("label_result")
        self.verticalLayout.addWidget(self.label_result)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    #--------------Addition Function-------------
    def add(self):
        firstnum = int(self.lineEdit_1st.text())
        secondnum = int(self.lineEdit_2nd.text())

        result = firstnum + secondnum
        self.label_result.setText("Addition : {}".format(result))

    #--------------Subtraction Function-------------
    def subtraction(self):
        firstnum = int(self.lineEdit_1st.text())
        secondnum = int(self.lineEdit_2nd.text())

        result = firstnum - secondnum
        self.label_result.setText("Subtraction : {}".format(result))

    #--------------Multiplication Function-------------
    def multiplication(self):
        firstnum = int(self.lineEdit_1st.text())
        secondnum = int(self.lineEdit_2nd.text())

        result = firstnum * secondnum
        self.label_result.setText("Multiplication : {}".format(result))

    #--------------dividition Function-------------
    def dividition(self):
        firstnum = int(self.lineEdit_1st.text())
        secondnum = int(self.lineEdit_2nd.text())

        result = firstnum / secondnum
        self.label_result.setText("Dividition : {}".format(result))
    

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "First Number:"))
        self.lineEdit_1st.setPlaceholderText(_translate("Form", "Enter First Number"))
        self.label_2.setText(_translate("Form", "Second Number:"))
        self.lineEdit_2nd.setPlaceholderText(_translate("Form", "Enter Second Number"))
        self.addbtn.setText(_translate("Form", "+"))
        self.subtractbtn.setText(_translate("Form", "-"))
        self.intobtn.setText(_translate("Form", "*"))
        self.dividbtn.setText(_translate("Form", "/"))
        self.label_result.setText(_translate("Form", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
