# Form implementation generated from reading ui file 'c:\Users\MD. SHAMIM\Documents\GitHub\Python-GUI-PyQt6\Section-05\AddMember.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import mysql.connector as mc


class Member_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(450, 450)
        Dialog.setStyleSheet("QDialog {\n"
"background-color: #f0f8ff\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"background-color:purple;\n"
"color: white\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)

        self.lineEdit_memberid = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_memberid.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_memberid.setFont(font)
        self.lineEdit_memberid.setObjectName("lineEdit_memberid")
        self.verticalLayout.addWidget(self.lineEdit_memberid)

        self.lineEdit_membername = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_membername.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_membername.setFont(font)
        self.lineEdit_membername.setObjectName("lineEdit_membername")

        self.verticalLayout.addWidget(self.lineEdit_membername)
        self.lineEdit_membermobile = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_membermobile.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_membermobile.setFont(font)
        self.lineEdit_membermobile.setObjectName("lineEdit_membermobile")
        int_validator = QtGui.QIntValidator()
        self.lineEdit_membermobile.setValidator(int_validator)
        # Set the maximum input length to 11 characters
        self.lineEdit_membermobile.setMaxLength(11)
        self.verticalLayout.addWidget(self.lineEdit_membermobile)

        self.lineEdit_memberemail = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_memberemail.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_memberemail.setFont(font)
        self.lineEdit_memberemail.setObjectName("lineEdit_memberemail")
        # Set email validator using QRegularExpressionValidator
        email_validator = QtGui.QRegularExpressionValidator(
            QtCore.QRegularExpression(r"[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}")
        )
        self.lineEdit_memberemail.setValidator(email_validator)
        self.verticalLayout.addWidget(self.lineEdit_memberemail)

        self.pushButton_addmemeber = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_addmemeber.clicked.connect(self.insert_member)
        self.pushButton_addmemeber.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.pushButton_addmemeber.setFont(font)
        self.pushButton_addmemeber.setStyleSheet("QPushButton {\n"
"background-color: purple;\n"
"color: white\n"
"}")
        self.pushButton_addmemeber.setObjectName("pushButton_addmemeber")
        self.verticalLayout.addWidget(self.pushButton_addmemeber)
        self.label_result = QtWidgets.QLabel(parent=Dialog)
        self.label_result.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_result.setFont(font)
        self.label_result.setText("")
        self.label_result.setObjectName("label_result")
        self.verticalLayout.addWidget(self.label_result)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)


    def insert_member(self):
                try:
                        mydb = mc.connect(
                                host = "localhost",
                                user="root",
                                password="",
                                database="library_managemenet"
                        )

                        memberid = self.lineEdit_memberid.text()
                        membername = self.lineEdit_membername.text()
                        membermobile = self.lineEdit_membermobile.text()
                        memberemail = self.lineEdit_memberemail.text()

                        if memberid =="" or membername =="" or membermobile == "" or memberemail =="":
                                self.label_result.setText("Please Fill all fields")
                                self.label_result.setStyleSheet("color: red")
                                return
                        
                        mycursor = mydb.cursor()
                        query = "INSERT INTO addmember_table (memberid, membername, membermobile, memberemail) VALUES (%s, %s, %s, %s)"
                        value = (memberid, membername, membermobile, memberemail)
                        mycursor.execute(query,value)

                        mydb.commit()
                        self.label_result.setText("Data added successfully")
                        self.label_result.setStyleSheet("color: green")

                        self.lineEdit_memberid.setText("")
                        self.lineEdit_membername.setText("")
                        self.lineEdit_membermobile.setText("")
                        self.lineEdit_memberemail.setText("")
                        
                except mc.Error as e:
                        self.label_result.setText("Failed to add Member")
                        self.label_result.setStyleSheet("color: red")


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Add Member"))
        self.label.setText(_translate("Dialog", "Enter Member Information"))
        self.lineEdit_memberid.setPlaceholderText(_translate("Dialog", "Please Enter Member ID"))
        self.lineEdit_membername.setPlaceholderText(_translate("Dialog", "Please Enter Member Name"))
        self.lineEdit_membermobile.setPlaceholderText(_translate("Dialog", "Please Enter Member Mobile"))
        self.lineEdit_memberemail.setPlaceholderText(_translate("Dialog", "Please Enter Member Email"))
        self.pushButton_addmemeber.setText(_translate("Dialog", "Add Memeber"))
