# Form implementation generated from reading ui file 'AddMember.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(450, 450)
        Dialog.setStyleSheet("QDialog {\n"
"background-color: #f0f8ff\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"background-color:purple;\n"
"color: white\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit_memberid = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_memberid.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_memberid.setFont(font)
        self.lineEdit_memberid.setObjectName("lineEdit_memberid")
        self.verticalLayout.addWidget(self.lineEdit_memberid)
        self.lineEdit_membername = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_membername.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_membername.setFont(font)
        self.lineEdit_membername.setObjectName("lineEdit_membername")
        self.verticalLayout.addWidget(self.lineEdit_membername)
        self.lineEdit_membermobile = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_membermobile.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_membermobile.setFont(font)
        self.lineEdit_membermobile.setObjectName("lineEdit_membermobile")
        self.verticalLayout.addWidget(self.lineEdit_membermobile)
        self.lineEdit_memberemail = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_memberemail.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_memberemail.setFont(font)
        self.lineEdit_memberemail.setStyleSheet("QLineEdit {\n"
"background-color: white\n"
"}")
        self.lineEdit_memberemail.setObjectName("lineEdit_memberemail")
        self.verticalLayout.addWidget(self.lineEdit_memberemail)
        self.pushButton_addmemeber = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_addmemeber.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.pushButton_addmemeber.setFont(font)
        self.pushButton_addmemeber.setStyleSheet("QPushButton {\n"
"background-color: purple;\n"
"color: white\n"
"}")
        self.pushButton_addmemeber.setObjectName("pushButton_addmemeber")
        self.verticalLayout.addWidget(self.pushButton_addmemeber)
        self.label_result = QtWidgets.QLabel(parent=Dialog)
        self.label_result.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_result.setFont(font)
        self.label_result.setText("")
        self.label_result.setObjectName("label_result")
        self.verticalLayout.addWidget(self.label_result)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Enter Member Information"))
        self.lineEdit_memberid.setPlaceholderText(_translate("Dialog", "Please Enter Member ID"))
        self.lineEdit_membername.setPlaceholderText(_translate("Dialog", "Please Enter Member Name"))
        self.lineEdit_membermobile.setPlaceholderText(_translate("Dialog", "Please Enter Member Mobile"))
        self.lineEdit_memberemail.setPlaceholderText(_translate("Dialog", "Please Enter Member Email"))
        self.pushButton_addmemeber.setText(_translate("Dialog", "Add Memeber"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
